version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - run: npm run test
            - run: npm run docs
workflows:
    build-and-test:
      jobs:
        - build-and-test
